"""Channel package for Engineering Flow Platform."""

from .jira import (
    jira_channel,
    JiraChannel,
    jira_get_issue,
    jira_search,
    jira_add_comment,
    jira_create_issue,
    jira_transition,
    jira_get_transitions,
    jira_get_comments,
    jira_update_issue,
    jira_assign_issue,
    jira_get_projects,
    jira_get_components,
    jira_get_versions,
    jira_get_worklog,
    jira_add_worklog,
)

from .confluence import (
    confluence_channel,
    ConfluenceChannel,
    confluence_get_page,
    confluence_search,
    confluence_create_page,
    confluence_update_page,
    confluence_get_comments,
    confluence_add_comment,
    confluence_list_spaces,
    confluence_delete_page,
    confluence_get_page_history,
    confluence_get_page_children,
    confluence_get_space,
    confluence_list_pages,
    confluence_get_user,
    confluence_watch_page,
    confluence_unwatch_page,
    confluence_search_by_title,
)

__all__ = [
    # Jira
    "jira_channel",
    "JiraChannel",
    "jira_get_issue",
    "jira_search",
    "jira_add_comment",
    "jira_create_issue",
    "jira_transition",
    "jira_get_transitions",
    "jira_get_comments",
    "jira_update_issue",
    "jira_assign_issue",
    "jira_get_projects",
    "jira_get_components",
    "jira_get_versions",
    "jira_get_worklog",
    "jira_add_worklog",
    # Confluence
    "confluence_channel",
    "ConfluenceChannel",
    "confluence_get_page",
    "confluence_search",
    "confluence_create_page",
    "confluence_update_page",
    "confluence_get_comments",
    "confluence_add_comment",
    "confluence_list_spaces",
    "confluence_delete_page",
    "confluence_get_page_history",
    "confluence_get_page_children",
    "confluence_get_space",
    "confluence_list_pages",
    "confluence_get_user",
    "confluence_watch_page",
    "confluence_unwatch_page",
    "confluence_search_by_title",
]
