"""Project runtime-profile data into external CLI configuration files."""

from __future__ import annotations

import hashlib
import json
import os
import stat
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from src.external_cli.github import github_hostname_from_base_url


_MANAGED_BY = "efp_runtime_profile"
_METADATA_VERSION = 1
_GIT_INCLUDE_BEGIN = "# BEGIN EFP_RUNTIME_PROFILE_GIT_INCLUDE"
_GIT_INCLUDE_END = "# END EFP_RUNTIME_PROFILE_GIT_INCLUDE"
_yaml = YAML()
_yaml.default_flow_style = False


def apply_runtime_profile_external_config(profile_config: dict[str, Any]) -> None:
    """Write external CLI config files for the sanitized Portal profile."""

    previous = _load_metadata()
    if previous:
        clear_runtime_profile_external_config(metadata=previous)

    metadata: dict[str, Any] = {"version": _METADATA_VERSION, "managed_by": _MANAGED_BY}
    wrote_any = False

    atlassian_config = _build_atlassian_config(profile_config)
    if atlassian_config is not None:
        path = _atlassian_config_path()
        text = json.dumps(atlassian_config, indent=2, sort_keys=True) + "\n"
        _write_private_text(path, text)
        metadata["atlassian"] = {"path": str(path), "sha256": _sha256_text(text)}
        wrote_any = True

    gh_entry = _build_gh_host_entry(profile_config)
    if gh_entry is not None:
        host, entry, token_sha = gh_entry
        hosts_path = _gh_hosts_path()
        hosts = _read_yaml_mapping(hosts_path)
        hosts[host] = entry
        _write_private_yaml(hosts_path, hosts)
        metadata["gh"] = {"path": str(hosts_path), "hosts": {host: {"token_sha256": token_sha}}}
        wrote_any = True

    git_user = _extract_git_user(profile_config)
    if git_user is not None:
        name, email = git_user
        generated_path = _generated_git_config_path()
        generated_text = f"[user]\n\tname = {_git_quote(name)}\n\temail = {_git_quote(email)}\n"
        _write_private_text(generated_path, generated_text)
        gitconfig_path = _gitconfig_path()
        _ensure_git_include(gitconfig_path, generated_path)
        metadata["git"] = {"gitconfig_path": str(gitconfig_path), "generated_path": str(generated_path)}
        wrote_any = True

    if wrote_any:
        _write_private_text(_metadata_path(), json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    else:
        _remove_file_if_exists(_metadata_path())


def clear_runtime_profile_external_config(*, metadata: dict[str, Any] | None = None) -> None:
    """Remove external CLI config previously generated by runtime profile apply."""

    meta = metadata if isinstance(metadata, dict) else _load_metadata()
    if not meta or meta.get("managed_by") != _MANAGED_BY:
        return

    atlassian = meta.get("atlassian") if isinstance(meta.get("atlassian"), dict) else {}
    atlassian_path = Path(str(atlassian.get("path") or "")) if atlassian.get("path") else None
    atlassian_sha = str(atlassian.get("sha256") or "")
    if atlassian_path and atlassian_path.exists() and _sha256_path(atlassian_path) == atlassian_sha:
        _remove_file_if_exists(atlassian_path)

    gh = meta.get("gh") if isinstance(meta.get("gh"), dict) else {}
    gh_path = Path(str(gh.get("path") or "")) if gh.get("path") else None
    gh_hosts = gh.get("hosts") if isinstance(gh.get("hosts"), dict) else {}
    if gh_path and gh_path.exists() and gh_hosts:
        hosts = _read_yaml_mapping(gh_path)
        changed = False
        for host, host_meta in gh_hosts.items():
            expected_sha = str((host_meta or {}).get("token_sha256") or "") if isinstance(host_meta, dict) else ""
            current = hosts.get(host)
            if isinstance(current, dict) and _sha256_text(str(current.get("oauth_token") or "")) == expected_sha:
                hosts.pop(host, None)
                changed = True
        if changed:
            if hosts:
                _write_private_yaml(gh_path, hosts)
            else:
                _remove_file_if_exists(gh_path)

    git = meta.get("git") if isinstance(meta.get("git"), dict) else {}
    generated_git = Path(str(git.get("generated_path") or "")) if git.get("generated_path") else None
    gitconfig_path = Path(str(git.get("gitconfig_path") or "")) if git.get("gitconfig_path") else None
    if gitconfig_path:
        _remove_git_include(gitconfig_path)
    if generated_git:
        _remove_file_if_exists(generated_git)

    _remove_file_if_exists(_metadata_path())


def _build_atlassian_config(profile_config: dict[str, Any]) -> dict[str, Any] | None:
    jira_instances = _build_product_instances(profile_config.get("jira"), product="jira")
    confluence_instances = _build_product_instances(profile_config.get("confluence"), product="confluence")
    if not jira_instances and not confluence_instances:
        return None
    return {
        "version": 1,
        "jira": {
            "default_instance": _default_instance_name(profile_config.get("jira"), jira_instances),
            "instances": jira_instances,
        },
        "confluence": {
            "default_instance": _default_instance_name(profile_config.get("confluence"), confluence_instances),
            "instances": confluence_instances,
        },
    }


def _build_product_instances(product_config: Any, *, product: str) -> list[dict[str, Any]]:
    if not isinstance(product_config, dict):
        return []
    if product_config.get("enabled") is False:
        return []
    raw_instances = product_config.get("instances")
    if not isinstance(raw_instances, list):
        return []
    instances: list[dict[str, Any]] = []
    used_names: set[str] = set()
    for index, raw in enumerate(raw_instances, 1):
        if not isinstance(raw, dict) or raw.get("enabled") is False:
            continue
        base_url = _normalize_base_url(raw.get("base_url") or raw.get("url"))
        if not base_url:
            continue
        name = _unique_instance_name(str(raw.get("name") or f"{product}-{index}").strip(), used_names, product, index)
        auth = _build_auth(raw)
        if product == "jira":
            api_version = "3" if str(raw.get("api_version") or "").strip() == "3" else "2"
            instance = {
                "name": name,
                "base_url": base_url,
                "api_version": api_version,
                "rest_path": str(raw.get("rest_path") or f"/rest/api/{api_version}"),
                "auth": auth,
            }
            default_project = _first_non_empty(raw, "default_project", "project", "project_key")
            if default_project:
                instance["default_project"] = default_project
        else:
            instance = {
                "name": name,
                "base_url": base_url,
                "rest_path": str(raw.get("rest_path") or "/rest/api"),
                "auth": auth,
            }
            default_space = _first_non_empty(raw, "default_space", "space", "space_key")
            if default_space:
                instance["default_space"] = default_space
        if "verify_ssl" in raw and isinstance(raw.get("verify_ssl"), bool):
            instance["verify_ssl"] = raw["verify_ssl"]
        ca_cert = _string_or_empty(raw.get("ca_cert"))
        if ca_cert:
            instance["ca_cert"] = ca_cert
        instances.append(instance)
    return instances


def _unique_instance_name(raw_name: str, used_names: set[str], product: str, index: int) -> str:
    candidate = raw_name or f"{product}-{index}"
    base = candidate
    suffix = 2
    while candidate in used_names:
        candidate = f"{base}-{suffix}"
        suffix += 1
    used_names.add(candidate)
    return candidate


def _default_instance_name(product_config: Any, instances: list[dict[str, Any]]) -> str:
    if not instances:
        return ""
    preferred = ""
    if isinstance(product_config, dict):
        preferred = str(product_config.get("default_instance") or "").strip()
    names = {str(item.get("name") or "") for item in instances}
    return preferred if preferred in names else str(instances[0].get("name") or "")


def _build_auth(raw: dict[str, Any]) -> dict[str, str]:
    username = _string_or_empty(raw.get("username"))
    password = _string_or_empty(raw.get("password"))
    api_key = _string_or_empty(raw.get("api_key") or raw.get("api_token"))
    token = _string_or_empty(raw.get("token") or raw.get("access_token"))
    if username and password:
        return {"type": "basic_password", "username": username, "password": password}
    if username and (api_key or token):
        return {"type": "basic_api_key", "username": username, "api_key": api_key or token}
    if token or api_key:
        return {"type": "bearer_token", "token": token or api_key}
    return {"type": ""}


def _build_gh_host_entry(profile_config: dict[str, Any]) -> tuple[str, dict[str, str], str] | None:
    github = profile_config.get("github") if isinstance(profile_config, dict) else None
    if not isinstance(github, dict) or github.get("enabled") is False:
        return None
    token = _string_or_empty(github.get("api_token") or github.get("token") or github.get("access_token"))
    if not token:
        return None
    host = github_hostname_from_base_url(_string_or_empty(github.get("api_base_url") or github.get("base_url")))
    entry = {"oauth_token": token, "git_protocol": "https"}
    return host, entry, _sha256_text(token)


def _extract_git_user(profile_config: dict[str, Any]) -> tuple[str, str] | None:
    git = profile_config.get("git") if isinstance(profile_config, dict) else None
    user = git.get("user") if isinstance(git, dict) and isinstance(git.get("user"), dict) else None
    if not isinstance(user, dict):
        return None
    name = _single_line(user.get("name"))
    email = _single_line(user.get("email"))
    if not name or not email:
        return None
    return name, email


def _normalize_base_url(value: Any) -> str:
    text = _string_or_empty(value)
    return text.rstrip("/")


def _first_non_empty(mapping: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = _string_or_empty(mapping.get(key))
        if value:
            return value
    return ""


def _string_or_empty(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _single_line(value: Any) -> str:
    return _string_or_empty(value).replace("\x00", "").replace("\r", " ").replace("\n", " ")


def _atlassian_config_path() -> Path:
    configured = os.environ.get("ATLASSIAN_CONFIG")
    return Path(configured).expanduser() if configured else Path.home() / ".config" / "atlassian" / "config.json"


def _gh_hosts_path() -> Path:
    gh_config_dir = os.environ.get("GH_CONFIG_DIR")
    base = Path(gh_config_dir).expanduser() if gh_config_dir else Path.home() / ".config" / "gh"
    return base / "hosts.yml"


def _gitconfig_path() -> Path:
    return Path(os.environ.get("GIT_CONFIG_GLOBAL") or Path.home() / ".gitconfig").expanduser()


def _generated_git_config_path() -> Path:
    return Path.home() / ".config" / "efp" / "runtime-profile.gitconfig"


def _metadata_path() -> Path:
    return Path.home() / ".config" / "efp" / "runtime-profile-external-config.json"


def _write_private_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write(text)
    _chmod_private(path)


def _write_private_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        _yaml.dump(payload, handle)
    _chmod_private(path)


def _read_yaml_mapping(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        loaded = _yaml.load(handle) or {}
    return loaded if isinstance(loaded, dict) else {}


def _chmod_private(path: Path) -> None:
    try:
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def _load_metadata() -> dict[str, Any]:
    path = _metadata_path()
    if not path.exists():
        return {}
    try:
        with path.open("r", encoding="utf-8") as handle:
            loaded = json.load(handle)
    except Exception:
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_path(path: Path) -> str:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return ""


def _remove_file_if_exists(path: Path) -> None:
    try:
        path.unlink()
    except FileNotFoundError:
        pass


def _git_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ensure_git_include(gitconfig_path: Path, generated_path: Path) -> None:
    gitconfig_path.parent.mkdir(parents=True, exist_ok=True)
    original = gitconfig_path.read_text(encoding="utf-8") if gitconfig_path.exists() else ""
    cleaned = _strip_git_include_block(original).rstrip()
    block = f"{_GIT_INCLUDE_BEGIN}\n[include]\n\tpath = {generated_path}\n{_GIT_INCLUDE_END}\n"
    new_text = f"{cleaned}\n\n{block}" if cleaned else block
    gitconfig_path.write_text(new_text, encoding="utf-8")
    _chmod_private(gitconfig_path)


def _remove_git_include(gitconfig_path: Path) -> None:
    if not gitconfig_path.exists():
        return
    original = gitconfig_path.read_text(encoding="utf-8")
    cleaned = _strip_git_include_block(original).strip()
    gitconfig_path.write_text((cleaned + "\n") if cleaned else "", encoding="utf-8")
    _chmod_private(gitconfig_path)


def _strip_git_include_block(text: str) -> str:
    lines = str(text or "").splitlines()
    out: list[str] = []
    skipping = False
    for line in lines:
        if line.strip() == _GIT_INCLUDE_BEGIN:
            skipping = True
            continue
        if skipping and line.strip() == _GIT_INCLUDE_END:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return "\n".join(out)
